// cities.js — the city registry the picker renders from. cities.json is
// GENERATED by worldripples/bake_city.py from the Python CityConfigs, so this file
// holds no city data of its own and cannot drift from the configs.

export async function loadCities(dataRoot) {
  // Missing/malformed cities.json must not break boot — same defensive posture
  // data.js already takes for districts and vehicle bins.
  try {
    const r = await fetch(`${dataRoot}/cities.json`);
    if (!r.ok) return null;
    const reg = await r.json();
    if (!reg || !Array.isArray(reg.cities) || reg.cities.length === 0) return null;
    return reg;
  } catch (_) {
    return null;
  }
}

// Returns the canonical slug string, or null when registry is falsy (the
// no-cities.json boot case) — callers must handle that null, not assume a string.
export function resolveSlug(registry, requested) {
  if (!registry) return null;
  if (requested) {
    const hit = registry.cities.find(
      (c) => c.slug.toLowerCase() === String(requested).toLowerCase()
    );
    if (hit) return hit.slug;
  }
  return registry.landing_default;
}

export function renderPicker(el, registry, activeSlug, onSelect) {
  el.replaceChildren();
  // Same defensive posture as loadCities: a null/malformed registry must not
  // throw here either — hide the picker and bail instead of assuming shape.
  if (!registry || !Array.isArray(registry.cities)) {
    el.hidden = true;
    return;
  }
  for (const city of registry.cities) {
    const b = document.createElement("button");
    b.type = "button";
    b.dataset.slug = city.slug;
    b.textContent = city.display_name;
    b.classList.toggle("active", city.slug === activeSlug);
    b.setAttribute("aria-pressed", String(city.slug === activeSlug));
    b.addEventListener("click", () => onSelect(city.slug));
    el.appendChild(b);
  }
  el.hidden = false;
}
